services:
  app:
    build: antipathya/contest-service
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8080:8080"
  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default
    ports:
      - "5436:5432"