// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/test.go

// Package mockRepository is a generated GoMock package.
package mockRepository

import (
	model "contest/internal/domain/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTestRepository is a mock of TestRepository interface.
type MockTestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTestRepositoryMockRecorder
}

// MockTestRepositoryMockRecorder is the mock recorder for MockTestRepository.
type MockTestRepositoryMockRecorder struct {
	mock *MockTestRepository
}

// NewMockTestRepository creates a new mock instance.
func NewMockTestRepository(ctrl *gomock.Controller) *MockTestRepository {
	mock := &MockTestRepository{ctrl: ctrl}
	mock.recorder = &MockTestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRepository) EXPECT() *MockTestRepositoryMockRecorder {
	return m.recorder
}

// AddTest mocks base method.
func (m *MockTestRepository) AddTest(ctx context.Context, taskID int, input, expectedResult string, points int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTest", ctx, taskID, input, expectedResult, points)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTest indicates an expected call of AddTest.
func (mr *MockTestRepositoryMockRecorder) AddTest(ctx, taskID, input, expectedResult, points interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTest", reflect.TypeOf((*MockTestRepository)(nil).AddTest), ctx, taskID, input, expectedResult, points)
}

// DeleteTest mocks base method.
func (m *MockTestRepository) DeleteTest(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTest", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTest indicates an expected call of DeleteTest.
func (mr *MockTestRepositoryMockRecorder) DeleteTest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTest", reflect.TypeOf((*MockTestRepository)(nil).DeleteTest), ctx, id)
}

// FindTestByID mocks base method.
func (m *MockTestRepository) FindTestByID(ctx context.Context, id int) (model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTestByID", ctx, id)
	ret0, _ := ret[0].(model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTestByID indicates an expected call of FindTestByID.
func (mr *MockTestRepositoryMockRecorder) FindTestByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTestByID", reflect.TypeOf((*MockTestRepository)(nil).FindTestByID), ctx, id)
}

// FindTestsByTaskID mocks base method.
func (m *MockTestRepository) FindTestsByTaskID(ctx context.Context, taskID int) ([]model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTestsByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTestsByTaskID indicates an expected call of FindTestsByTaskID.
func (mr *MockTestRepositoryMockRecorder) FindTestsByTaskID(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTestsByTaskID", reflect.TypeOf((*MockTestRepository)(nil).FindTestsByTaskID), ctx, taskID)
}

// GetTests mocks base method.
func (m *MockTestRepository) GetTests(ctx context.Context) ([]model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTests", ctx)
	ret0, _ := ret[0].([]model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTests indicates an expected call of GetTests.
func (mr *MockTestRepositoryMockRecorder) GetTests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTests", reflect.TypeOf((*MockTestRepository)(nil).GetTests), ctx)
}

// UpdateTest mocks base method.
func (m *MockTestRepository) UpdateTest(ctx context.Context, id int, newItem model.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTest", ctx, id, newItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTest indicates an expected call of UpdateTest.
func (mr *MockTestRepositoryMockRecorder) UpdateTest(ctx, id, newItem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTest", reflect.TypeOf((*MockTestRepository)(nil).UpdateTest), ctx, id, newItem)
}
